### ISSUE TITLE
Princípios

### ISSUE THREAD

**Issue by lucasmation** [ipea/ipeaDATA_20#1]
(anotações de nossa reunião de hoje, vão complementando)

a) Ergonomicidade
-- Busca como carro chefe
-- No máximo 3 cliques
b) Hospedagem em Cloud
c) usabilidade por celular
d) feijão com arroz
e) modularidade
f) controle de versão: github (público) ( com devidos cuidados)
g) de fácil manutenção
h) programação bem documentada

**Comment by gubasso** [comment]
já coloquei esse conteudo no readme.md
