### ISSUE TITLE
Finalizar pesquisa com a alternativa do Gitlab CI (Ferramentas de CI)

### ISSUE THREAD

**Issue by GuiFay** [ipea/ipeaDATA_20#15]
Finalizar pesquisa com a alternativa do Gitlab CI

**Comment by gubasso** [comment]
@BrunoRangel30 , essa aqui já está finalizada?

**Comment by BrunoRangel30** [comment]
A parte teórica sim , mais para bater o martelo eu o Guilherme queremos fazer um teste prático.

**Comment by gubasso** [comment]
Blz! Vamos fechar essa até sexta-feira e apresentar pro @lucasmation , blz?

**Comment by BrunoRangel30** [comment]
ok..tudo bem
