### ISSUE TITLE
problemas site ipeadata1.0

### ISSUE THREAD

**Issue by lucasmation** [ipea/ipeaDATA_20#2]
(anoatações reunião de hoje, complementem)

Problemas
- arvore de classificação VS. tags e busca
- separar sistema de classificação como um metadado, não hard-coded
- multiplicação vertical de séries
- Padrão de sites do governo (regras de cabeçalho
- Acessibilidade e demais regras do Governo

- Ao fazer busca a opção “macroeconômico” já está selecionada (devia ser genérico

**Comment by gubasso** [comment]
adicionei esse conteudo no readme.md do projeto
