### ISSUE TITLE
mandar requisitos para orçamento para rodar na nuvem

### ISSUE THREAD

**Issue by lucasmation** [ipea/ipeaDATA_20#3]
**Link para a documentação do orçamento:** https://docs.google.com/document/d/1RN20qrpsR5HkTuHnNkN2GhWNM0_kfPN6AplRuvgXPbw/edit?usp=sharing

------
- [x] especificar os custos considerando as métricas de transferências de dados
- [x] especificar os custos considerando Balanceamento de Carga

- [x] elencar todos os sistemas que farão parte do core do Ipea Data que irá para a Cloud
    - sistemas mais centrais (acredito que aqueles sistemas gerentes não entrariam)
    - os sistemas em volta poderão ter uma comunicação por api com o core central
- [x] coletar recursos de máquinas (alocação)
- [x] coletar relatório de acessos
- [x] fazer a estimativa em cloud, considerando:
    - um uso constante dos recursos contratados
    - um uso _on-demand_ dos recursos (modulando as máquinas em função dos acessos) da forma mais dinâmica possível (objetivo de minimizar os custos)
      - [x] Estimativa Amazon
      - [x] Estimativa Google
- [x] Adicionar um multiplicador governo `[ (preço PJ normal) * 2 ou * 3]`
- [x] comparar com uma estimativa de custo atual dos recursos que temos

----
# Anotações Lucas Mation

(anotações da reunião de hoje, por favor complementem)
- Relatório de acesso (tx. De acessos, tx. De requisições)
- Máquina que hospeda o ipeadata é a mesma que hospeda o banco
    - O banco faz regra de negócios?
    - Pg Recurso do Banco

**Comment by micheljunio** [comment]
@lucasmation você já conseguiu reunir a documentação do ipeaDATA ou parte dela ? se sim, por favor, adicione no repositório ou nós envie por mail ;) vlw

**Comment by lucasmation** [comment]
estou colocando em: 

(deletei o caminho, nenhuma pasta de rede deve ficar pública aqui no github)
(mandei por email para vocês, junto com outros links)

**Comment by lucasmation** [comment]
Só para vocês saberem, os códigos  de ETL (importação de dados, etc) do Ipeadata estão em: 
https://github.com/Ipeadata
Mas importante: isso tudo é do banco de dados para trás. Nosso foco tem que ser do banco para frente

**Comment by gubasso** [comment]
Pessoal, como conversado, ficou faltando só a parte do comparativo com o google cloud (coloquei esse item ali da descrição da issue.

@lucasmation , o link pra documentação do orçamento está aqui (também coloquei na documentação da issue): https://docs.google.com/document/d/1RN20qrpsR5HkTuHnNkN2GhWNM0_kfPN6AplRuvgXPbw/edit?usp=sharing
