### ISSUE TITLE
Verificar pertinencia de instalar o Node.js no servidor de Desenv (= homologação 1)

### ISSUE THREAD

**Issue by lucasmation** [ipea/ipeaDATA_20#32]
Conforme conversei com o Gustavo, gostaria que vocês pensassem bem se é necessário  mesmo instalar o Node.js no servidor de desenvolvimento (dentro do Ipea), pois o pessoal da TI já ficou preocupado, por ser algo que eles não dominam e vão ter que instalar, entender etc. 

Conversem entre sí sobre os prós e contras.

**Comment by gubasso** [comment]
@lucasmation , já conversei com os meninos e eles já ajustaram o e-pedidos.

No servidor vai ficar instalado somente o servidor de aplicação da Apache (tomcat), que o ipea já usa.

Usaremos o node nas nossas máquinas locais para o desenvolvimento da aplicação.

De toda forma, vou conversar com o Fernando e apresentar pra ele a explicação da nossa proposta de tecnologia e deixar ele bater o martelo.
