### ISSUE TITLE
Apresentar Stack tecnologico proposto para T.I. do Ipea

### ISSUE THREAD

**Issue by lucasmation** [ipea/ipeaDATA_20#33]
Na reunião da proxima sexta o Fernando Tb vai participar. A idéia seria apresentar o stack de technologias, frameworks, ambiente, etc para a nossa TI. 

@gubasso , você pode prepara uma apresentação/proposta para discutirmos com o Fernando?

Lembrando que nosso objetivo é sempre simplificar o meio de campo. Tanto do nosso lado como do lado deles

**Comment by gubasso** [comment]
Disponibilizei a apresentação em: https://github.com/ipea/ipeaDATA_20/blob/master/docs/React.pptx
