### ISSUE TITLE
E-pedidos para Servidor de desenvolvimento

### ISSUE THREAD

**Issue by GuiFay** [ipea/ipeaDATA_20#35]
criar um e-pedido para a máquina onde hosperará o servidor do IPEADATA 2.0

**Comment by BrunoRangel30** [comment]
E-pedidos 139510 concluido

**Comment by GuiFay** [comment]
será instalado somente o apache tomcat nessa máquina

**Comment by BrunoRangel30** [comment]
e-pedido criado  N° 139510
