### ISSUE TITLE
Explorar toda a documentação atual (colabore e svn) e mapear a arquitetura atual do sistema

### ISSUE THREAD

**Issue by gubasso** [ipea/ipeaDATA_20#4]
Link para a documentação gerada com o diagnóstico da arquitetura atual: https://docs.google.com/document/d/1lHZyLZkDVuc75_pDvbb51zowJCGEkzriHL3_oW0VmxE/edit?usp=sharing

---
- [x] corrigir/atualizar documentação atual
- [x] ler toda a documentação do colabore e svn
- [x] documentar de forma esquemática / sintética / resumida a arquitetura/infra atual do projeto
- [x] fechar o diagnóstico de toda a parte tecnológica que abarca o projeto atual

**Comment by GuiFay** [comment]
Arquitetura Atual:
![alt text](http://i.imgur.com/LTQ4NNE.png
"Arq_atual")

**Comment by BrunoRangel30** [comment]
Tópicos  de duvidas para Reunião (15/02/2017) 

https://docs.google.com/document/d/1np8-RnVtXegXokgBuflkYyT3l-QN2Gr6YSi44x-Rlng/edit?usp=sharing

**Comment by gubasso** [comment]
A pedido do @lucasmation , adicionei mais uma pendência nessa issue, pra que a gente faça correções/atualizações na documentação atual, dada a pesquisa que realizamos para o diagnóstico da situação do projeto.
