### ISSUE TITLE
Propor nova arquitetura / infra para o IpeaDATA 2.0

### ISSUE THREAD

**Issue by gubasso** [ipea/ipeaDATA_20#5]
A partir do diagnóstico feito (depende de #4 ), propor nova arquitetura e infra (processos, tecnologias, etc...) para a versão 2.0 (e demais projetos de tecnologia do IPEA).

**Comment by GuiFay** [comment]
Proposta de Arquitetura:

![alt text](http://i.imgur.com/pVxw7S7.png
"Arq_proposta")

**Comment by gubasso** [comment]
Vou marcar como feita. A infra macro já foi definida (de acordo com a figura). A estrutura do frontend em si será fechada quando batermos o martelo na tecnologia e no protótipo.
